### ISSUE TITLE
Crash when attempting to boot Pokémon

### ISSUE THREAD

**Issue by GoddessMaria15** [alyosha-tas/GBAHawk#5]
OS: Windows 11 Home 22H2 (22621.1992)
Version: GBAHawk 1.5

So I have been trying to get the Gen 3 Pokemon games (Ruby/Sapphire/Emerald/FireRed/LeafGreen) to load... only for GBAHawk to crash on the BIOS screen when trying to load them. I was able to get an error message to appear once, but not again after this.

---

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at BizHawk.Emulation.Cores.Nintendo.GBA.GBAHawk.GetSamplesSync(Int16[]& samples, Int32& nsamp)
   at BizHawk.Client.Common.SoundOutputProvider.GetSamplesFromBase(Double& scaleFactor)
   at BizHawk.Client.Common.SoundOutputProvider.GetSamples(Int32 idealSampleCount)
   at BizHawk.Client.Common.SoundOutputProvider.GetSamples(Int32 idealSampleCount, Int16[]& samples, Int32& sampleCount)
   at BizHawk.Client.GBAHawk.Sound.UpdateSound(Single atten, Boolean isSecondaryThrottlingDisabled)
   at BizHawk.Client.GBAHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.GBAHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.GBAHawk.Program.SubMain(String[] args)

---

Out of curiosity, I did try a few other games (Castlevania AoS, Castlevania HoD, Yu-Gi-Oh! Duel Monsters 6 Expert 2, and Sonic Advance). They all loaded without any problems. Is there any possible way to get Pokémon up and running?

**Comment by Fortranm** [comment]
![image](https://github.com/alyosha-tas/GBAHawk/assets/19356108/1a027b5d-43d7-4a02-913f-d883340a3abc)
Adding to this, the game actually boots in GBAHawkLink, but this shows up at the beginning and the game can't save.

**Comment by alyosha-tas** [comment]
I released version 1.5.1 which fixes the crashes. Gen 3 games don't have RTC yet, but shjould otherwise work.

**Comment by Fortranm** [comment]
The game can now start, but FireRed still gets stuck (softlock?) when trying to save.

**Comment by alyosha-tas** [comment]
Hmm, looks like a mistake in the flash mapper, simple fix, thanks for the report. Fix will be out with the RTC fix.

**Comment by alyosha-tas** [comment]
Version 1.6 is released which has implementation for RTC.

You can also disable RTC from the settings.

Saving is also fixed.

Please test version 1.6.
